### PR TITLE
Refactoring: using namespaces and autoload

### PR DESCRIPTION
**Pull request by williamokano**
Hi, I refactored your code in order to be compatible with composer as a lib (you can now publish on packgist).

I removed all the manual require_once's and fixed some code in order to being compatible with namespaces.

Also, I had to change the folders structure (actually, I just put the code folder under the src folder, so I could use PSR-4 autoload).

I know that still a lot of things to improve, but it's functional.

### CODE REVIEW

**Comment by gfviegas** [comment]
Spetacular!!! +1 👍

**Comment by Confectrician** [comment]
Dafuq. I just recognized "Ah a pull request" and then saw the huge amount of removings and additions.
Great work. :+1:

**Comment by williamokano** [comment]
@Confectrician thanks m8

@tan-tan-kanarek could you check? thanks :)

**Comment by tan-tan-kanarek** [comment]
Hey,
Although it is a great idea, I think you better maintain it as a different fork and therefore also as a different library.
* I don't want to break compatibility for those who already use the library.
* You removed files and recreated them elsewhere instead of moving them, which caused lose of credits to all the developers who worked on these files so far.
* The library won't work without composer.

I strongly recommend that you'll publish it as a different library for composer users.

**Comment by williamokano** [comment]
It's ok, that's why I open the pull request on a branch.

**Pull request closed without merging**
